### ISSUE TITLE
Installation and deployment issues with the 2.7.0.0

### ISSUE THREAD

**Issue by 7octal** [OCSInventory-NG/WindowsAgent#171]
### General information
Operating system :  Windows 10 x64, Windows 7 x64, Windows Server 2016

### OCS Inventory information
Windows agent version : 2.7.0.0

### Problem's description

- The 2.7.0.0 version doesn't upgrade the previous versions : the previous versions remain in the Windows "Add/remove programs" and trying to uninstall them there will just uninstall the new version;

- Using the OCS Deployment Tool with the 2.7.0.0 fails every time with the error "Unable to open or read setup log on remote host". This doesn't prevent, sometimes, the agent from installing thou. Still, it's quite random now.

These two issues seem somehow related to the fact that the 2.7.0.0 version has a different name than usual (there is no "NG" in its name).

**Comment by Tarbos** [comment]
I had the same issues, it seems that download.exe is not properly killed thus that file and some required DLLs are in use and can not be overwritten. Afterwards every deployment throws a BAD_DIGEST_ERROR.

**Comment by bigben386** [comment]
2.7.0.0 is also not registering as a windows service for me. I have tried manual and silent installs via the CLI. The issue has mostly been on new PCs. No errors are shown in the installer.

**Comment by mtbadi39** [comment]
Salam Alikom ;
We have the same issues as @7octal  and @Tarbos 

- The previous versions remain in the Windows "Add/remove programs"
- Every deployment throws a BAD_DIGEST_ERROR

**Comment by charleneauger** [comment]
Hi,

A new version 2.7.0.1 of the windows agent is available ! We fixed the bug with the previous version.

Best regards,
Charlene Auger

**Comment by bigben386** [comment]
@charleneauger 2.7.0.1 still does not remove the old versions from  programs and features.
![image](https://user-images.githubusercontent.com/9749364/88391383-17fe2780-cd88-11ea-8f5d-63d24ec1710a.png)

**Comment by charleneauger** [comment]
Hi @bigben386 ,
Thanks for your fast report, I'm fixing that now !

**Comment by charleneauger** [comment]
@bigben386 ,

The 2.7.0.1 release has been updated. 

Best regards,
Charlene Auger

**Comment by bigben386** [comment]
This update did remove the old entry from programs and features but it is not upgrading the service properly. The service executable still is version 2.7.0.0 after the update. I watched the installer stop the 2.7.0.0 service and later start the 2.7.0.0 service.
[OCS-Windows-Agent-Setup-x64.log](https://github.com/OCSInventory-NG/WindowsAgent/files/4972960/OCS-Windows-Agent-Setup-x64.log)
seems like only the service is not updated.
PS C:\Program Files\OCS Inventory Agent> gci . -Filter "*.exe" | select -ExpandProperty versioninfo

ProductVersion   FileVersion      FileName
--------------   -----------      --------
2.7.0.1          2.7.0.1          C:\Program Files\OCS Inventory Agent\Download.exe
2.7.0.1          2.7.0.1          C:\Program Files\OCS Inventory Agent\OCSInventory.exe
2.7.0.1          2.7.0.1          C:\Program Files\OCS Inventory Agent\OcsNotifyUser.exe
2.7.0.0          2.7.0.0          C:\Program Files\OCS Inventory Agent\OcsService.exe
2.7.0.1          2.7.0.1          C:\Program Files\OCS Inventory Agent\OcsSystray.exe
                 2.7.0.1          C:\Program Files\OCS Inventory Agent\uninst.exe

**Comment by charleneauger** [comment]
Hi @bigben386 ,

I can't reproduce your problem. I installed 2.6.0.1, next 2.7.0 and last 2.7.0.1 on multiple computer and the service is correctly updated. I advise you to uninstall/install OCS Agent properly.

Best regards,
Charlene Auger

**Comment by bigben386** [comment]
@charleneauger I found an issue with the update on my PC. The Dell Support Assist for Business had an open handle on the ocsservice.exe. I will set 2.7.0.1 to deploy to all our computers and will see if all the new PCs show up in OCS.

**Comment by bigben386** [comment]
@charleneauger I was able to get a successful upgrade of all executables after uninstalling the dell supportassist for business.

**Comment by charleneauger** [comment]
Hi @bigben386 ,

Thank you for your report ! I close this issue :)

Regards,
Charlene Auger
