### ISSUE TITLE
Duplicate entries

### ISSUE THREAD

**Issue by samirmeh** [OCSInventory-NG/WindowsAgent#87]
### General information
Operating system :  
OS Name : Microsoft Windows 10 Pro
OS Version : 10.0.17134
Windows user :User

### OCS Inventory information
Windows agent version : 2.3.1.1

### Problem's description
We experience an issue where OCS Agent decides to generate a new unique ID when he detects network interface change. This produces duplicates very often (almost daily). As far as I can make it out from the agent logs the agent detects changes and lists the MAC addresses multiple times. Taking into account the timestamps it looks like it happens while people might be switching from ethernet to wireless or turning on VPN.
Additionally do notice the timestamp difference between 2 entries I am pasting below: only 4 minutes apart (this coincides with our VPN testing).
I am adding the server log as well if it helps with the debugging.

### Inventory log file ( optional )
Agent log file: https://pastebin.com/XvagPZqN
Server log file: https://pastebin.com/TuXpK0hG

**Comment by rchaconmolero** [comment]
We have the same problem with Agent 2.4.0.0 and Windows 10/Windows 7. 
OCS Server 2.5. Every day lots of computers appear duplicate in ocs server with the sme logs and behaviour. This bug is not closed in 2.4 version of windows agent.

**Comment by charleneauger** [comment]
Hi @samirmeh @rchaconmolero ,
This bug has been fixed with PR #79 .
Regards,
Charlene Auger

**Comment by rchaconmolero** [comment]
We have ocs agent version 2.4 and we still have the same problem. The problem is not resolve with 
PR #79. Reinstall agents not resolve the problem.

Any help, please?.

Agent log file: 

Starting OCS Inventory NG Agent on Wednesday, January 16, 2019 08:12:13.
AGENT => Running OCS Inventory NG Agent Version 2.4.0.0
AGENT => Using OCS Inventory NG FrameWork Version 2.4.0.0
AGENT => Loading plug-in(s)
	DLL PLUGIN => Searching for Plug-in DLL(s) in folder <C:\Program Files (x86)\OCS Inventory Agent\plugins>
	DLL PLUGIN => 0 DLL Plug-in(s) successfully loaded on 0 DLL(s) found
AGENT => Using network connection with Communication Server
	COM PROVIDER => Loading Communication Provider <C:\Program Files (x86)\OCS Inventory Agent\ComHTTP.dll>
AGENT => Using Communication Provider <OCS Inventory NG cURL Communication Provider> Version <2.4.0.0>
AGENT => Sending Prolog
	DID_CHECK => Read DeviceID <CS1794-2018-06-20-19-37-03> and MACs <78:33:20:52:41:5374:D2:20:52:41:5300:1F:D0:A5:30:32> in file <ocsinventory.dat>
DID_CHECK => MAC Address changed new:<A6:A2:20:52:41:5300:1F:D0:A5:30:32> old:<78:33:20:52:41:5374:D2:20:52:41:5300:1F:D0:A5:30:32>
DID_CHECK => Generating new unique ID for device <CS1794>
	DID_CHECK => writing DeviceID <CS1794-2019-01-16-08-12-13> and MACs <A6:A2:20:52:41:5300:1F:D0:A5:30:32> in file <C:\ProgramData\OCS Inventory NG\Agent\ocsinventory.dat>
